2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_setup.py:_flush():76] Configure stats pid to 13015
2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_setup.py:_flush():76] Loading settings from /home/sadbhawna/.config/wandb/settings
2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_setup.py:_flush():76] Loading settings from /home/sadbhawna/Desktop/cs6910_assignment1/wandb/settings
2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'question1_plot_images.py', 'program_abspath': '/home/sadbhawna/Desktop/cs6910_assignment1/question1_plot_images.py', 'program': '/home/sadbhawna/Desktop/cs6910_assignment1/question1_plot_images.py'}
2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_init.py:_log_setup():526] Logging user logs to /home/sadbhawna/Desktop/cs6910_assignment1/wandb/run-20240225_154608-1tqrbp6f/logs/debug.log
2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_init.py:_log_setup():527] Logging internal logs to /home/sadbhawna/Desktop/cs6910_assignment1/wandb/run-20240225_154608-1tqrbp6f/logs/debug-internal.log
2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_init.py:init():566] calling init triggers
2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_init.py:init():616] starting backend
2024-02-25 15:46:08,892 INFO    MainThread:13015 [wandb_init.py:init():620] setting up manager
2024-02-25 15:46:08,896 INFO    MainThread:13015 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-25 15:46:08,897 INFO    MainThread:13015 [wandb_init.py:init():628] backend started and connected
2024-02-25 15:46:08,903 INFO    MainThread:13015 [wandb_init.py:init():720] updated telemetry
2024-02-25 15:46:08,908 INFO    MainThread:13015 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-25 15:46:09,477 ERROR   MainThread:13015 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-25 15:46:09,676 ERROR   MainThread:13015 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/sadbhawna/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/sadbhawna/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-02-25 15:46:10,682 WARNING MsgRouterThr:13015 [router.py:message_loop():77] message_loop has been closed
